trigger: none  # Disable CI trigger for manual or scheduled runs

pool:
  name: Default

variables:
  workingDirectory: 'env/QA'
  serviceConnection: 'dhdp-infra-sp'
  backendResourceGroup: 'dhdp-lab-resource-group'
  backendStorageAccount: 'dhdplabsa'
  backendContainerName: 'tfstate'
  backendKey: 'qa.terraform.tfstate'

stages:
  - template: .azure-pipelines/templates/init-stage.yml
    parameters:
      terraformVersion: '1.5.7'

  - template: .azure-pipelines/templates/validate-stage.yml
    parameters:
      terraformVersion: '1.5.7'

  - template: .azure-pipelines/templates/plan-stage.yml
    parameters:
      terraformVersion: '1.5.7'

  - template: .azure-pipelines/templates/apply-stage.yml
    parameters:
      terraformVersion: '1.5.7'

  - template: .azure-pipelines/templates/output-stage.yml
    parameters:
      terraformVersion: '1.5.7'

  # Optional: uncomment to enable destroy in CI
  # - template: .azure-pipelines/templates/destroy-stage.yml
  #   parameters:
  #     terraformVersion: '1.5.7'
