trigger: none

pool:
  name: Default

variables:
  workingDirectory: 'env/QA'
  serviceConnection: 'dhdp-infra-sp'
  backendResourceGroup: 'dhdp-lab-resource-group'
  backendStorageAccount: 'dhdplabsa'
  backendContainerName: 'tfstate'
  backendKey: 'qa.terraform.tfstate'

stages:
  - stage: Init
    displayName: 'Terraform Init'
    jobs:
      - job: Init
        steps:
          - checkout: self
            persistCredentials: true

          - script: |
              rm -rf .terraform
              rm -f .terraform.lock.hcl
            displayName: 'Clean .terraform and lockfile'

          - script: |
              echo "##vso[task.setvariable variable=ARM_USE_OIDC]true"
              echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$(servicePrincipalId)"
              echo "##vso[task.setvariable variable=ARM_TENANT_ID]$(tenantId)"
              echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(subscriptionId)"
            displayName: 'Set OIDC Auth Variables'

          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: '1.5.7'

          - script: terraform -version
            displayName: 'Show Terraform Version'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(workingDirectory)'
              backendServiceArm: '$(serviceConnection)'
              backendAzureRmResourceGroupName: '$(backendResourceGroup)'
              backendAzureRmStorageAccountName: '$(backendStorageAccount)'
              backendAzureRmContainerName: '$(backendContainerName)'
              backendAzureRmKey: '$(backendKey)'
              backendAzureRmUseOIDC: true
              useTerraformVersion: '1.5.7'

  - stage: Validate
    displayName: 'Terraform Validate'
    dependsOn: Init
    jobs:
      - job: Validate
        steps:
          - checkout: self
            persistCredentials: true

          - script: |
              rm -rf .terraform
              rm -f .terraform.lock.hcl
            displayName: 'Clean .terraform and lockfile'

          - script: |
              echo "##vso[task.setvariable variable=ARM_USE_OIDC]true"
              echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$(servicePrincipalId)"
              echo "##vso[task.setvariable variable=ARM_TENANT_ID]$(tenantId)"
              echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(subscriptionId)"
            displayName: 'Set OIDC Auth Variables'

          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: '1.5.7'

          - script: terraform -version
            displayName: 'Show Terraform Version'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Init (Validate)'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(workingDirectory)'
              backendServiceArm: '$(serviceConnection)'
              backendAzureRmResourceGroupName: '$(backendResourceGroup)'
              backendAzureRmStorageAccountName: '$(backendStorageAccount)'
              backendAzureRmContainerName: '$(backendContainerName)'
              backendAzureRmKey: '$(backendKey)'
              backendAzureRmUseOIDC: true
              useTerraformVersion: '1.5.7'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(workingDirectory)'
              environmentServiceNameAzureRM: '$(serviceConnection)'
              useTerraformVersion: '1.5.7'

  - stage: Plan
    displayName: 'Terraform Plan'
    dependsOn: Validate
    jobs:
      - job: Plan
        steps:
          - checkout: self
            persistCredentials: true

          - script: |
              rm -rf .terraform
              rm -f .terraform.lock.hcl
            displayName: 'Clean .terraform and lockfile'

          - script: |
              echo "##vso[task.setvariable variable=ARM_USE_OIDC]true"
              echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$(servicePrincipalId)"
              echo "##vso[task.setvariable variable=ARM_TENANT_ID]$(tenantId)"
              echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(subscriptionId)"
            displayName: 'Set OIDC Auth Variables'

          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: '1.5.7'

          - script: terraform -version
            displayName: 'Show Terraform Version'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Init (Plan)'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(workingDirectory)'
              backendServiceArm: '$(serviceConnection)'
              backendAzureRmResourceGroupName: '$(backendResourceGroup)'
              backendAzureRmStorageAccountName: '$(backendStorageAccount)'
              backendAzureRmContainerName: '$(backendContainerName)'
              backendAzureRmKey: '$(backendKey)'
              backendAzureRmUseOIDC: true
              useTerraformVersion: '1.5.7'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(workingDirectory)'
              environmentServiceNameAzureRM: '$(serviceConnection)'
              publishPlanResults: true
              planOutput: 'tfplan.out'
              varsFile: 'qa.tfvars'
              useTerraformVersion: '1.5.7'
  - stage: Destroy
    displayName: 'Terraform Destroy'
    dependsOn: Plan
    jobs:
      - job: Destroy
        steps:
          - checkout: self
            persistCredentials: true

          - script: |
              rm -rf .terraform
              rm -f .terraform.lock.hcl
            displayName: 'Clean .terraform and lockfile'

          - script: |
              echo "##vso[task.setvariable variable=ARM_USE_OIDC]true"
              echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$(servicePrincipalId)"
              echo "##vso[task.setvariable variable=ARM_TENANT_ID]$(tenantId)"
              echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(subscriptionId)"
            displayName: 'Set OIDC Auth Variables'

          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: '1.5.7'

          - script: terraform -version
            displayName: 'Show Terraform Version'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Init (Destroy)'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(workingDirectory)'
              backendServiceArm: '$(serviceConnection)'
              backendAzureRmResourceGroupName: '$(backendResourceGroup)'
              backendAzureRmStorageAccountName: '$(backendStorageAccount)'
              backendAzureRmContainerName: '$(backendContainerName)'
              backendAzureRmKey: '$(backendKey)'
              backendAzureRmUseOIDC: true
              useTerraformVersion: '1.5.7'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Destroy'
            inputs:
              provider: 'azurerm'
              command: 'destroy'
              workingDirectory: '$(workingDirectory)'
              environmentServiceNameAzureRM: '$(serviceConnection)'
              useTerraformVersion: '1.5.7'
              varsFile: 'qa.tfvars'
              commandOptions: '-auto-approve'


